kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq
roleRef:
  kind: ClusterRole
  name: rabbitmq
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: rabbitmq
